### ISSUE TITLE
bug on german systems

### ISSUE THREAD

**Issue by S4ftl4den** [Caylis1397/Syncrio#3]
hi. I have syncing issues on german windows systems. actually i kind of know what the issue is but can ofc not change your code. apparently when syncing the science amount to the groupmembers, you use the systems standard floating point separator which is a point (.) in english. unfortuantely the standard floating point separator seems to be a comma (,) on german systems. this results in, when reading the value later the ingame science becomes not 13.3334 but instead 133334 because it somehow cant read the comma. well at least thats my guess because when i change the separator in the Currency.txt on server side and replace the 
0
0
17,40833

with

0
0
17.40833

it all works fine again. also whenever this bug happens it resets the entire research progress and everything can be researched again. i do not know why this happens.

regards

**Comment by Caylis1397** [comment]
Ok, so I through a update together in about ten minutes, but it should work. It makes all the string conversions use the US English culture. In other words it should force it to use only one culture, meaning that it will read and write the data in the same way. The only unknown is how KSP will take the data...
Anyways here the link [https://github.com/Caylis1397/Syncrio/tree/Culture-support/Release%20Files/Downloads](url). You will need to update both the client and the server, but your scenario files should work fine. Provided you set the comma back to a point first. I hope this helps! But if it doesn't work I'll see what I can do.

**Comment by S4ftl4den** [comment]
It seems to work for one person. Later I will give a multiuser report on this. For now the values definetly are written with the point as separator which makes KSP recognize them properly. Thanks you.

**Comment by S4ftl4den** [comment]
Okay the error with the science points becoming millions is resolved. For some reason the science done still gets resetted all the time so that you can do every research infinite times. Unfortuantely in this case I have no idea what causes it.

**Comment by S4ftl4den** [comment]
Okay the error with the science points becoming millions is resolved. For some reason the science projects still get resetted all the time so that you can do every project infinite times (always just doing EVA or surface sample at launchpad for example). Unfortuantely in this case I have no idea what causes it. It also seems to "refresh" at random. Sometimes it stays correct for a while (but that could also just be locally). As soon as it refreshes with the server everything is gone again.

In case u need any information on contents of files on the server just notice me. I am watching this thread and will inform you.

I just reassured this. Sometimes it loads correctly on start but then somehow loses the data even midflight ironicly.

**Comment by Caylis1397** [comment]
Okay, so if I understood the problem right, then I think I fixed it. However, I have no idea if this update will really change anything... If it does not work then I'll need to see the "ScienceRecieved.txt" from your groups scenario files. But I hope it works though, either way you will need to update both the client and the server again. For some reason I'm getting a error 404  from the old link, but if it works for you, then you can get the new files using it.

**Comment by S4ftl4den** [comment]
Aaaaan doesnt work. I dont really get it. Sometimes the server shows the already researched projects fine sometimes it doesnt show any at all. After a while everybody on the server is certain to have no projects (like EVA on Launchpad) shown in their science lab.
The strange thing is the "Science Received" file still shows everything. Unfortunately this only gets loaded into the individual players data sometimes and most of the times not.

Sci : surfaceSample@KerbinSrfLandedLaunchPad
Value : 30
SciNode
{
id = surfaceSample@KerbinSrfLandedLaunchPad
title = Surface Sample from LaunchPad
dsc = 1
scv = 0.25
sbv = 0.300000012
sci = 9
cap = 12
}
Sci : evaReport@KerbinSrfLandedLaunchPad
Value : 8
SciNode
{
id = evaReport@KerbinSrfLandedLaunchPad
title = EVA Report from LaunchPad
dsc = 1
scv = 0
sbv = 0.300000012
sci = 2.4000001
cap = 2.4000001
}
Sci : surfaceSample@KerbinSrfLandedCrawlerway
Value : 30
SciNode
{
id = surfaceSample@KerbinSrfLandedCrawlerway
title = Surface Sample from Crawlerway
dsc = 1
scv = 0.25
sbv = 0.300000012
sci = 9
cap = 12
}
Sci : evaReport@KerbinSrfLandedCrawlerway
Value : 8
SciNode
{
id = evaReport@KerbinSrfLandedCrawlerway
title = EVA Report from Crawlerway
dsc = 1
scv = 0
sbv = 0.300000012
sci = 2.4000001
cap = 2.4000001
}
Sci : recovery@KerbinFlew
Value : 1
SciNode
{
id = recovery@KerbinFlew
title = Recovery of a vessel that survived a flight.
dsc = 1
scv = 0.166666672
sbv = 5
sci = 5
cap = 6
}
Sci : evaReport@KerbinFlyingHigh
Value : 8
SciNode
{
id = evaReport@KerbinFlyingHigh
title = EVA Report from Kerbin's upper atmosphere
dsc = 1
scv = 0
sbv = 0.899999976
sci = 7.19999981
cap = 7.19999981
}
Sci : recovery@KerbinSubOrbited
Value : 1
SciNode
{
id = recovery@KerbinSubOrbited
title = Recovery of a vessel after a sub-orbital flight.
dsc = 1
scv = 0.166666701
sbv = 8
sci = 8
cap = 9.60000038
}


Are there any logfiles that might help you?

**Comment by Caylis1397** [comment]
Yes that's the logfile I was looking for, but the data is correct. Which means that something is wrong with the interface with KSP. Are you using Dark Multiplayer? Because if so that might explain some of the problem. Dark Multiplayer keeps it's own record of your science data. Which means that you might get the correct data when you join the servers, but while playing, Syncrio (if it's have problems handling the data) might override the data with nothing. I'll look into the interface with KSP and see what I can do to fix this. Sorry for the inconvenience.

**Comment by Caylis1397** [comment]
Okay, so I looked into the interface between KSP and Syncrio and I don't think there is much I can do to fix this bug at the moment. But when KSP 1.3 officially comes out, I should be able to fix it. Sorry but you may have to wait on this one. KSP 1.3 adds localization support and that should allow me to fix this

**Comment by S4ftl4den** [comment]
Yeah I am using dark multiplayer. Okay but what you are saying is that generally everybody who uses Syncrio with DMP will likely experience this problem at one point right. Then at least we are nocht alone :D

**Comment by S4ftl4den** [comment]
Hey. So did you get around to fixing this by now? I think the update is through right? =)

**Comment by Caylis1397** [comment]
To start, sorry I did not respond for so long. And to answer your question, I believe it is fixed now. But I still have no way to test it. Although, another user on a non-English OS did say that it is fixed for them. Also, as a side note, culture support branch has been merged with the main branch, so the fix in the main release.
